/**
 * Mock for exercise-gif-registry.ts
 * Updated to match the new MP4-based MuscleWiki registry.
 * Values are string URLs (not numeric IDs) to match the real registry.
 */

const MW = "https://media.musclewiki.com/media/uploads/videos/branded";

export const EXERCISE_GIFS: Record<string, string> = {
  "male-Barbell-barbell-close-grip-bench-press-front": `${MW}/male-Barbell-barbell-close-grip-bench-press-front.mp4`,
  "male-Barbell-barbell-close-grip-bench-press-side": `${MW}/male-Barbell-barbell-close-grip-bench-press-side.mp4`,
  "male-Barbell-barbell-incline-bench-press-front": `${MW}/male-Barbell-barbell-incline-bench-press-front.mp4`,
  "male-Barbell-barbell-incline-bench-press-side": `${MW}/male-Barbell-barbell-incline-bench-press-side.mp4`,
  "male-Dumbbells-dumbbell-weighted-dip-front": `${MW}/male-Dumbbells-dumbbell-weighted-dip-front.mp4`,
  "male-Dumbbells-dumbbell-weighted-dip-side": `${MW}/male-Dumbbells-dumbbell-weighted-dip-side.mp4`,
  "male-barbell-bench-press-front": `${MW}/male-barbell-bench-press-front.mp4`,
  "male-barbell-bench-press-side": `${MW}/male-barbell-bench-press-side.mp4`,
  "male-bodyweight-bench-dips-front": `${MW}/male-bodyweight-bench-dips-front.mp4`,
  "male-bodyweight-bench-dips-side": `${MW}/male-bodyweight-bench-dips-side.mp4`,
  "male-bodyweight-push-up-front": `${MW}/male-bodyweight-push-up-front.mp4`,
  "male-bodyweight-push-up-side": `${MW}/male-bodyweight-push-up-side.mp4`,
  "male-cable-pec-fly-front": `${MW}/male-cable-pec-fly-front.mp4`,
  "male-cable-pec-fly-side": `${MW}/male-cable-pec-fly-side.mp4`,
  "male-dumbbell-chest-fly-front": `${MW}/male-dumbbell-chest-fly-front.mp4`,
  "male-dumbbell-chest-fly-side": `${MW}/male-dumbbell-chest-fly-side.mp4`,
  "male-dumbbell-decline-bench-press-front": `${MW}/male-dumbbell-decline-bench-press-front.mp4`,
  "male-dumbbell-decline-bench-press-side": `${MW}/male-dumbbell-decline-bench-press-side.mp4`,
  "male-dumbbell-incline-bench-press-front": `${MW}/male-dumbbell-incline-bench-press-front.mp4`,
  "male-dumbbell-incline-bench-press-side": `${MW}/male-dumbbell-incline-bench-press-side.mp4`,
  "male-Barbell-barbell-bent-over-row-front": `${MW}/male-Barbell-barbell-bent-over-row-front.mp4`,
  "male-Barbell-barbell-bent-over-row-side": `${MW}/male-Barbell-barbell-bent-over-row-side.mp4`,
  "male-Barbell-barbell-deadlift-front": `${MW}/male-Barbell-barbell-deadlift-front.mp4`,
  "male-Barbell-barbell-deadlift-side": `${MW}/male-Barbell-barbell-deadlift-side.mp4`,
  "male-Barbell-barbell-romanian-deadlift-front": `${MW}/male-Barbell-barbell-romanian-deadlift-front.mp4`,
  "male-Barbell-barbell-romanian-deadlift-side": `${MW}/male-Barbell-barbell-romanian-deadlift-side.mp4`,
  "male-Barbell-barbell-sumo-deadlift-front": `${MW}/male-Barbell-barbell-sumo-deadlift-front.mp4`,
  "male-Barbell-barbell-sumo-deadlift-side": `${MW}/male-Barbell-barbell-sumo-deadlift-side.mp4`,
  "male-Barbell-landmine-t-bar-rows-front": `${MW}/male-Barbell-landmine-t-bar-rows-front.mp4`,
  "male-Barbell-landmine-t-bar-rows-side": `${MW}/male-Barbell-landmine-t-bar-rows-side.mp4`,
  "male-Dumbbells-dumbbell-pendlay-row-front": `${MW}/male-Dumbbells-dumbbell-pendlay-row-front.mp4`,
  "male-Dumbbells-dumbbell-pendlay-row-side": `${MW}/male-Dumbbells-dumbbell-pendlay-row-side.mp4`,
  "male-barbell-stiff-leg-deadlift-front": `${MW}/male-barbell-stiff-leg-deadlift-front.mp4`,
  "male-barbell-stiff-leg-deadlift-side": `${MW}/male-barbell-stiff-leg-deadlift-side.mp4`,
  "male-bodyweight-chin-ups-front": `${MW}/male-bodyweight-chin-ups-front.mp4`,
  "male-bodyweight-chin-ups-side": `${MW}/male-bodyweight-chin-ups-side.mp4`,
  "male-bodyweight-pull-ups-front": `${MW}/male-bodyweight-pull-ups-front.mp4`,
  "male-bodyweight-pull-ups-side": `${MW}/male-bodyweight-pull-ups-side.mp4`,
  "male-dumbbell-row-bilateral-front": `${MW}/male-dumbbell-row-bilateral-front.mp4`,
  "male-dumbbell-row-bilateral-side": `${MW}/male-dumbbell-row-bilateral-side.mp4`,
  "male-machine-pulldown-front": `${MW}/male-machine-pulldown-front.mp4`,
  "male-machine-pulldown-side": `${MW}/male-machine-pulldown-side.mp4`,
  "male-machine-seated-cable-row-front": `${MW}/male-machine-seated-cable-row-front.mp4`,
  "male-machine-seated-cable-row-side": `${MW}/male-machine-seated-cable-row-side.mp4`,
  "male-Barbell-barbell-overhead-press-front": `${MW}/male-Barbell-barbell-overhead-press-front.mp4`,
  "male-Barbell-barbell-overhead-press-side": `${MW}/male-Barbell-barbell-overhead-press-side.mp4`,
  "male-Cable-cable-rope-face-pulls-front": `${MW}/male-Cable-cable-rope-face-pulls-front.mp4`,
  "male-Cable-cable-rope-face-pulls-side": `${MW}/male-Cable-cable-rope-face-pulls-side.mp4`,
  "male-Dumbbells-dumbbell-arnold-press-front": `${MW}/male-Dumbbells-dumbbell-arnold-press-front.mp4`,
  "male-Dumbbells-dumbbell-arnold-press-side": `${MW}/male-Dumbbells-dumbbell-arnold-press-side.mp4`,
  "male-Dumbbells-dumbbell-overhead-press-front": `${MW}/male-Dumbbells-dumbbell-overhead-press-front.mp4`,
  "male-Dumbbells-dumbbell-overhead-press-side": `${MW}/male-Dumbbells-dumbbell-overhead-press-side.mp4`,
  "male-Dumbbells-dumbbell-shrug-front": `${MW}/male-Dumbbells-dumbbell-shrug-front.mp4`,
  "male-Dumbbells-dumbbell-shrug-side": `${MW}/male-Dumbbells-dumbbell-shrug-side.mp4`,
  "male-Kettlebells-kettlebell-upright-row-front": `${MW}/male-Kettlebells-kettlebell-upright-row-front.mp4`,
  "male-Kettlebells-kettlebell-upright-row-side": `${MW}/male-Kettlebells-kettlebell-upright-row-side.mp4`,
  "male-dumbbell-front-raise-front": `${MW}/male-dumbbell-front-raise-front.mp4`,
  "male-dumbbell-front-raise-side": `${MW}/male-dumbbell-front-raise-side.mp4`,
  "male-dumbbell-lateral-raise-front": `${MW}/male-dumbbell-lateral-raise-front.mp4`,
  "male-dumbbell-lateral-raise-side": `${MW}/male-dumbbell-lateral-raise-side.mp4`,
  "male-dumbbell-rear-delt-fly-front": `${MW}/male-dumbbell-rear-delt-fly-front.mp4`,
  "male-dumbbell-rear-delt-fly-side": `${MW}/male-dumbbell-rear-delt-fly-side.mp4`,
  "male-Barbell-barbell-curl-front": `${MW}/male-Barbell-barbell-curl-front.mp4`,
  "male-Barbell-barbell-curl-side": `${MW}/male-Barbell-barbell-curl-side.mp4`,
  "male-Dumbbells-dumbbell-curl-front": `${MW}/male-Dumbbells-dumbbell-curl-front.mp4`,
  "male-Dumbbells-dumbbell-curl-side": `${MW}/male-Dumbbells-dumbbell-curl-side.mp4`,
  "male-Dumbbells-dumbbell-leg-curl-front": `${MW}/male-Dumbbells-dumbbell-leg-curl-front.mp4`,
  "male-Dumbbells-dumbbell-leg-curl-side": `${MW}/male-Dumbbells-dumbbell-leg-curl-side.mp4`,
  "male-Dumbbells-dumbbell-preacher-curl-front": `${MW}/male-Dumbbells-dumbbell-preacher-curl-front.mp4`,
  "male-Dumbbells-dumbbell-preacher-curl-side": `${MW}/male-Dumbbells-dumbbell-preacher-curl-side.mp4`,
  "male-dumbbell-concentration-curl-front": `${MW}/male-dumbbell-concentration-curl-front.mp4`,
  "male-dumbbell-concentration-curl-side": `${MW}/male-dumbbell-concentration-curl-side.mp4`,
  "male-dumbbell-hammer-curl-front": `${MW}/male-dumbbell-hammer-curl-front.mp4`,
  "male-dumbbell-hammer-curl-side": `${MW}/male-dumbbell-hammer-curl-side.mp4`,
  "male-Bands-band-overhead-tricep-extension-front": `${MW}/male-Bands-band-overhead-tricep-extension-front.mp4`,
  "male-Bands-band-overhead-tricep-extension-side": `${MW}/male-Bands-band-overhead-tricep-extension-side.mp4`,
  "male-Bodyweight-bodyweight-tricep-extension-front": `${MW}/male-Bodyweight-bodyweight-tricep-extension-front.mp4`,
  "male-Bodyweight-bodyweight-tricep-extension-side": `${MW}/male-Bodyweight-bodyweight-tricep-extension-side.mp4`,
  "male-Kettlebells-kettlebell-skull-crusher-front": `${MW}/male-Kettlebells-kettlebell-skull-crusher-front.mp4`,
  "male-Kettlebells-kettlebell-skull-crusher-side": `${MW}/male-Kettlebells-kettlebell-skull-crusher-side.mp4`,
  "male-Machine-machine-tricep-pushdown-front": `${MW}/male-Machine-machine-tricep-pushdown-front.mp4`,
  "male-Machine-machine-tricep-pushdown-side": `${MW}/male-Machine-machine-tricep-pushdown-side.mp4`,
  "male-Barbell-barbell-front-squat-olympic-front": `${MW}/male-Barbell-barbell-front-squat-olympic-front.mp4`,
  "male-Barbell-barbell-front-squat-olympic-side": `${MW}/male-Barbell-barbell-front-squat-olympic-side.mp4`,
  "male-Barbell-barbell-hip-thrust-front": `${MW}/male-Barbell-barbell-hip-thrust-front.mp4`,
  "male-Barbell-barbell-hip-thrust-side": `${MW}/male-Barbell-barbell-hip-thrust-side.mp4`,
  "male-Barbell-barbell-reverse-lunge-front": `${MW}/male-Barbell-barbell-reverse-lunge-front.mp4`,
  "male-Barbell-barbell-reverse-lunge-side": `${MW}/male-Barbell-barbell-reverse-lunge-side.mp4`,
  "male-Barbell-barbell-squat-front": `${MW}/male-Barbell-barbell-squat-front.mp4`,
  "male-Barbell-barbell-squat-side": `${MW}/male-Barbell-barbell-squat-side.mp4`,
  "male-Bodyweight-walking-lunge-front": `${MW}/male-Bodyweight-walking-lunge-front.mp4`,
  "male-Bodyweight-walking-lunge-side": `${MW}/male-Bodyweight-walking-lunge-side.mp4`,
  "male-Kettlebells-kettlebell-seated-calf-raise-front": `${MW}/male-Kettlebells-kettlebell-seated-calf-raise-front.mp4`,
  "male-Kettlebells-kettlebell-seated-calf-raise-side": `${MW}/male-Kettlebells-kettlebell-seated-calf-raise-side.mp4`,
  "male-Kettlebells-kettlebell-step-up-front": `${MW}/male-Kettlebells-kettlebell-step-up-front.mp4`,
  "male-Kettlebells-kettlebell-step-up-side": `${MW}/male-Kettlebells-kettlebell-step-up-side.mp4`,
  "male-Machine-machine-hack-squat-front": `${MW}/male-Machine-machine-hack-squat-front.mp4`,
  "male-Machine-machine-hack-squat-side": `${MW}/male-Machine-machine-hack-squat-side.mp4`,
  "male-bodyweight-bulgarian-split-squat-front": `${MW}/male-bodyweight-bulgarian-split-squat-front.mp4`,
  "male-bodyweight-bulgarian-split-squat-side": `${MW}/male-bodyweight-bulgarian-split-squat-side.mp4`,
  "male-bodyweight-forward-lunge-front_zb4K50d": `${MW}/male-bodyweight-forward-lunge-front_zb4K50d.mp4`,
  "male-bodyweight-forward-lunge-front": `${MW}/male-bodyweight-forward-lunge-front.mp4`,
  "male-bodyweight-forward-lunge-side": `${MW}/male-bodyweight-forward-lunge-side.mp4`,
  "male-bodyweight-glute-bridge-front": `${MW}/male-bodyweight-glute-bridge-front.mp4`,
  "male-bodyweight-glute-bridge-side": `${MW}/male-bodyweight-glute-bridge-side.mp4`,
  "male-dumbbell-goblet-squat-front": `${MW}/male-dumbbell-goblet-squat-front.mp4`,
  "male-dumbbell-goblet-squat-side": `${MW}/male-dumbbell-goblet-squat-side.mp4`,
  "male-machine-leg-extension-front": `${MW}/male-machine-leg-extension-front.mp4`,
  "male-machine-leg-extension-side": `${MW}/male-machine-leg-extension-side.mp4`,
  "male-machine-leg-press-front": `${MW}/male-machine-leg-press-front.mp4`,
  "male-machine-leg-press-side": `${MW}/male-machine-leg-press-side.mp4`,
  "male-machine-standing-calf-raises-front": `${MW}/male-machine-standing-calf-raises-front.mp4`,
  "male-machine-standing-calf-raises-side": `${MW}/male-machine-standing-calf-raises-side.mp4`,
  "male-Bodyweight-bicycle-crunch-front": `${MW}/male-Bodyweight-bicycle-crunch-front.mp4`,
  "male-Bodyweight-bicycle-crunch-side": `${MW}/male-Bodyweight-bicycle-crunch-side.mp4`,
  "male-Bodyweight-dead-bug-front": `${MW}/male-Bodyweight-dead-bug-front.mp4`,
  "male-Bodyweight-dead-bug-side": `${MW}/male-Bodyweight-dead-bug-side.mp4`,
  "male-Bodyweight-elbow-side-plank-front": `${MW}/male-Bodyweight-elbow-side-plank-front.mp4`,
  "male-Bodyweight-elbow-side-plank-side": `${MW}/male-Bodyweight-elbow-side-plank-side.mp4`,
  "male-Bodyweight-floor-incline-leg-raise-front": `${MW}/male-Bodyweight-floor-incline-leg-raise-front.mp4`,
  "male-Bodyweight-floor-incline-leg-raise-side": `${MW}/male-Bodyweight-floor-incline-leg-raise-side.mp4`,
  "male-Bodyweight-mountain-climber-front": `${MW}/male-Bodyweight-mountain-climber-front.mp4`,
  "male-Bodyweight-mountain-climber-side": `${MW}/male-Bodyweight-mountain-climber-side.mp4`,
  "male-Bodyweight-situp-front": `${MW}/male-Bodyweight-situp-front.mp4`,
  "male-Bodyweight-situp-side": `${MW}/male-Bodyweight-situp-side.mp4`,
  "male-Kettlebells-kettlebell-russian-twist-front": `${MW}/male-Kettlebells-kettlebell-russian-twist-front.mp4`,
  "male-Kettlebells-kettlebell-russian-twist-side": `${MW}/male-Kettlebells-kettlebell-russian-twist-side.mp4`,
  "male-TRX-trx-ab-rollout-front": `${MW}/male-TRX-trx-ab-rollout-front.mp4`,
  "male-TRX-trx-ab-rollout-side": `${MW}/male-TRX-trx-ab-rollout-side.mp4`,
  "male-bodyweight-crunch-front": `${MW}/male-bodyweight-crunch-front.mp4`,
  "male-bodyweight-crunch-side": `${MW}/male-bodyweight-crunch-side.mp4`,
  "male-bodyweight-forearm-plank-front": `${MW}/male-bodyweight-forearm-plank-front.mp4`,
  "male-bodyweight-forearm-plank-side": `${MW}/male-bodyweight-forearm-plank-side.mp4`,
  "male-bodyweight-hanging-knee-raises-front": `${MW}/male-bodyweight-hanging-knee-raises-front.mp4`,
  "male-bodyweight-hanging-knee-raises-side": `${MW}/male-bodyweight-hanging-knee-raises-side.mp4`,
  "male-cable-woodchopper-front": `${MW}/male-cable-woodchopper-front.mp4`,
  "male-cable-woodchopper-side": `${MW}/male-cable-woodchopper-side.mp4`,
  "male-Bodyweight-burpee-front": `${MW}/male-Bodyweight-burpee-front.mp4`,
  "male-Bodyweight-burpee-side": `${MW}/male-Bodyweight-burpee-side.mp4`,
  "male-Cardio-cardio-jumping-jacks-front": `${MW}/male-Cardio-cardio-jumping-jacks-front.mp4`,
  "male-Cardio-cardio-jumping-jacks-side": `${MW}/male-Cardio-cardio-jumping-jacks-side.mp4`,
  "male-Cardio-jump-rope-front": `${MW}/male-Cardio-jump-rope-front.mp4`,
  "male-Cardio-jump-rope-side": `${MW}/male-Cardio-jump-rope-side.mp4`,
  "male-Cardio-treadmill-sprint-front": `${MW}/male-Cardio-treadmill-sprint-front.mp4`,
  "male-Cardio-treadmill-sprint-side": `${MW}/male-Cardio-treadmill-sprint-side.mp4`,
  "male-Kettlebells-kettlebell-swing-front": `${MW}/male-Kettlebells-kettlebell-swing-front.mp4`,
  "male-Kettlebells-kettlebell-swing-side": `${MW}/male-Kettlebells-kettlebell-swing-side.mp4`,
  "male-Plyometrics-box-jump-front": `${MW}/male-Plyometrics-box-jump-front.mp4`,
  "male-Plyometrics-box-jump-side": `${MW}/male-Plyometrics-box-jump-side.mp4`,
};

/**
 * @deprecated Side views now live in EXERCISE_GIFS with -side suffix.
 * Kept empty for backward compatibility.
 */
export const SIDE_VIEW_GIFS: Record<string, string> = {};

/**
 * Look up the MP4 video URL for an exercise, with optional angle toggle.
 */
export function getExerciseVideoUrl(
  frontKey: string,
  angle: "front" | "side" = "front"
): string {
  if (angle === "front") {
    return EXERCISE_GIFS[frontKey] ?? EXERCISE_GIFS["male-bodyweight-push-up-front"];
  }
  const sideKey = frontKey.replace(/-front$/, "-side");
  return (
    EXERCISE_GIFS[sideKey] ??
    EXERCISE_GIFS[frontKey] ??
    EXERCISE_GIFS["male-bodyweight-push-up-front"]
  );
}

