/**
 * Shopping List PDF/Text Export Module
 *
 * Generates a branded PDF or shareable text version of the AI-generated
 * shopping suggestions from the Pantry feature.
 */
import { Platform, Share, Alert } from "react-native";

export interface ShoppingExportItem {
  name: string;
  category: string;
  estimatedCost: string;
  priority: "essential" | "recommended" | "nice-to-have";
  reason: string;
  mealsEnabled: string[];
}

// ── Text Export ──────────────────────────────────────────────────────

export function generateShoppingListText(
  items: ShoppingExportItem[],
  userName?: string,
): string {
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let text = `🛒 PeakPulse Shopping List\n`;
  text += `${date}\n`;
  if (userName) text += `For: ${userName}\n`;
  text += `${"─".repeat(40)}\n\n`;

  // Group by priority
  const essential = items.filter(i => i.priority === "essential");
  const recommended = items.filter(i => i.priority === "recommended");
  const niceToHave = items.filter(i => i.priority === "nice-to-have");

  if (essential.length > 0) {
    text += `⭐ ESSENTIAL (Must Buy)\n`;
    essential.forEach(item => {
      text += `  □ ${item.name} — ${item.estimatedCost}\n`;
      text += `    ${item.reason}\n`;
    });
    text += `\n`;
  }

  if (recommended.length > 0) {
    text += `✅ RECOMMENDED\n`;
    recommended.forEach(item => {
      text += `  □ ${item.name} — ${item.estimatedCost}\n`;
      text += `    ${item.reason}\n`;
    });
    text += `\n`;
  }

  if (niceToHave.length > 0) {
    text += `💡 NICE TO HAVE\n`;
    niceToHave.forEach(item => {
      text += `  □ ${item.name} — ${item.estimatedCost}\n`;
      text += `    ${item.reason}\n`;
    });
    text += `\n`;
  }

  text += `${"─".repeat(40)}\n`;
  text += `Total items: ${items.length}\n`;
  text += `Generated by PeakPulse AI\n`;

  return text;
}

// ── Share as Text ──────────────────────────────────────────────────

export async function shareShoppingListAsText(
  items: ShoppingExportItem[],
  userName?: string,
): Promise<void> {
  const text = generateShoppingListText(items, userName);

  try {
    await Share.share({
      message: text,
      title: "PeakPulse Shopping List",
    });
  } catch (err) {
    Alert.alert("Share Error", "Could not share the shopping list.");
  }
}

// ── PDF Export ──────────────────────────────────────────────────────

function generateShoppingListHTML(
  items: ShoppingExportItem[],
  userName?: string,
): string {
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const essential = items.filter(i => i.priority === "essential");
  const recommended = items.filter(i => i.priority === "recommended");
  const niceToHave = items.filter(i => i.priority === "nice-to-have");

  function renderSection(title: string, icon: string, color: string, sectionItems: ShoppingExportItem[]): string {
    if (sectionItems.length === 0) return "";
    return `
      <div style="margin-bottom: 24px;">
        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 2px solid ${color};">
          <span style="font-size: 20px;">${icon}</span>
          <h2 style="margin: 0; color: ${color}; font-size: 18px; font-weight: 700;">${title}</h2>
          <span style="background: ${color}20; color: ${color}; font-size: 12px; padding: 2px 8px; border-radius: 10px; font-weight: 600;">${sectionItems.length} items</span>
        </div>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #f8f8f8;">
              <th style="text-align: left; padding: 8px 12px; font-size: 12px; color: #666; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">Item</th>
              <th style="text-align: left; padding: 8px 12px; font-size: 12px; color: #666; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">Category</th>
              <th style="text-align: right; padding: 8px 12px; font-size: 12px; color: #666; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">Est. Cost</th>
            </tr>
          </thead>
          <tbody>
            ${sectionItems.map((item, idx) => `
              <tr style="border-bottom: 1px solid #eee; ${idx % 2 === 1 ? "background: #fafafa;" : ""}">
                <td style="padding: 10px 12px;">
                  <div style="display: flex; align-items: center; gap: 8px;">
                    <span style="width: 18px; height: 18px; border: 2px solid ${color}; border-radius: 4px; display: inline-block; flex-shrink: 0;"></span>
                    <div>
                      <div style="font-weight: 600; color: #1a1a1a; font-size: 14px;">${item.name}</div>
                      <div style="font-size: 11px; color: #888; margin-top: 2px;">${item.reason}</div>
                      ${item.mealsEnabled.length > 0 ? `<div style="font-size: 10px; color: ${color}; margin-top: 3px;">Enables: ${item.mealsEnabled.slice(0, 3).join(", ")}</div>` : ""}
                    </div>
                  </div>
                </td>
                <td style="padding: 10px 12px; font-size: 12px; color: #666;">${item.category}</td>
                <td style="padding: 10px 12px; text-align: right; font-weight: 600; color: #1a1a1a; font-size: 13px;">${item.estimatedCost}</td>
              </tr>
            `).join("")}
          </tbody>
        </table>
      </div>
    `;
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; padding: 0; }
        @page { margin: 20mm 15mm; }
      </style>
    </head>
    <body>
      <!-- Header -->
      <div style="background: linear-gradient(135deg, #1a0a00 0%, #2d1800 50%, #1a0a00 100%); padding: 32px 28px; margin: -20mm -15mm 24px -15mm; color: white;">
        <div style="display: flex; justify-content: space-between; align-items: flex-start;">
          <div>
            <div style="font-size: 12px; color: #F59E0B; font-weight: 600; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 6px;">PeakPulse AI</div>
            <h1 style="font-size: 28px; font-weight: 800; margin-bottom: 4px; color: #FBBF24;">Shopping List</h1>
            <div style="font-size: 13px; color: rgba(255,255,255,0.7);">${date}</div>
            ${userName ? `<div style="font-size: 13px; color: rgba(255,255,255,0.7); margin-top: 2px;">Prepared for: ${userName}</div>` : ""}
          </div>
          <div style="text-align: right;">
            <div style="font-size: 36px; font-weight: 800; color: #F59E0B;">${items.length}</div>
            <div style="font-size: 11px; color: rgba(255,255,255,0.6); text-transform: uppercase; letter-spacing: 1px;">Items</div>
          </div>
        </div>
      </div>

      <!-- Summary Bar -->
      <div style="display: flex; gap: 12px; margin-bottom: 24px;">
        ${essential.length > 0 ? `<div style="flex: 1; background: #FEF3C7; border-radius: 10px; padding: 12px; text-align: center; border: 1px solid #FDE68A;">
          <div style="font-size: 20px; font-weight: 800; color: #92400E;">${essential.length}</div>
          <div style="font-size: 10px; color: #92400E; font-weight: 600; text-transform: uppercase;">Essential</div>
        </div>` : ""}
        ${recommended.length > 0 ? `<div style="flex: 1; background: #DCFCE7; border-radius: 10px; padding: 12px; text-align: center; border: 1px solid #BBF7D0;">
          <div style="font-size: 20px; font-weight: 800; color: #166534;">${recommended.length}</div>
          <div style="font-size: 10px; color: #166534; font-weight: 600; text-transform: uppercase;">Recommended</div>
        </div>` : ""}
        ${niceToHave.length > 0 ? `<div style="flex: 1; background: #DBEAFE; border-radius: 10px; padding: 12px; text-align: center; border: 1px solid #BFDBFE;">
          <div style="font-size: 20px; font-weight: 800; color: #1E40AF;">${niceToHave.length}</div>
          <div style="font-size: 10px; color: #1E40AF; font-weight: 600; text-transform: uppercase;">Nice to Have</div>
        </div>` : ""}
      </div>

      <!-- Sections -->
      ${renderSection("Essential — Must Buy", "⭐", "#D97706", essential)}
      ${renderSection("Recommended", "✅", "#16A34A", recommended)}
      ${renderSection("Nice to Have", "💡", "#2563EB", niceToHave)}

      <!-- Footer -->
      <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; text-align: center;">
        <div style="font-size: 11px; color: #999;">Generated by PeakPulse AI • ${date}</div>
        <div style="font-size: 10px; color: #ccc; margin-top: 4px;">Smart shopping suggestions based on your pantry inventory and nutritional goals</div>
      </div>
    </body>
    </html>
  `;
}

export async function exportShoppingListPdf(
  items: ShoppingExportItem[],
  userName?: string,
): Promise<void> {
  try {
    const html = generateShoppingListHTML(items, userName);

    if (Platform.OS === "web") {
      // Web: open print dialog
      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.print();
      }
      return;
    }

    // Native: use expo-print + expo-sharing
    const Print = await import("expo-print");
    const Sharing = await import("expo-sharing");

    const { uri } = await Print.printToFileAsync({
      html,
      base64: false,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: "PeakPulse Shopping List",
        UTI: "com.adobe.pdf",
      });
    } else {
      Alert.alert("PDF Generated", `Shopping list saved to: ${uri}`);
    }
  } catch (err) {
    console.error("[ShoppingPDF] Export error:", err);
    Alert.alert("Export Error", "Could not generate the shopping list PDF. Please try again.");
  }
}
